In [ ]:
# Import necessary libraries
import numpy as np
from sklearn.preprocessing import OneHotEncoder

# Sample categorical data (each value represents a category)
data = np.array([['Red'], ['Blue'], ['Green'], ['Red'], ['Green']])

# Create a OneHotEncoder object
encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the data and transform it
one_hot_encoded_data = encoder.fit_transform(data)

# Print the original and one-hot encoded data
print("Original Data:")
print(data)
print("\nOne-Hot Encoded Data:")
print(one_hot_encoded_data)

Original Data:
[['Red']
 ['Blue']
 ['Green']
 ['Red']
 ['Green']]

One-Hot Encoded Data:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
